GET http://localhost:3000/api/unit
content-type: application/json

###
POST http://localhost:3000/api/unit
content-type: application/json

{
    "unit_name": "PCS"
}
###
PUT http://localhost:3000/api/unit/1
content-type: application/json

{
    "unit_name": "KG"
}

###
DELETE http://localhost:3000/api/unit/1